FROM ruby:3.0.0

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /app

RUN apt-get update

COPY Gemfile Gemfile.lock ./
RUN gem install bundler:2.2.26 && bundle install

COPY . .

CMD exe/simple-api
