#!/usr/bin/env bash

[[ ! -z ${PORT+z} ]] && echo "Running on port $PORT" || PORT=4567

# Heroku supplies a $PORT on new deploys, otherwise use 4567

bundle exec ruby lib/simple_api/main.rb -s Puma -p $PORT
